version: 5.1.0
variant: default
logo: 
    text: Flc゛
head:
    favicon: /assets/images/favicon.ico
    manifest:
        name: 叶子坑
        short_name: Flc
        start_url: "./?utm_source=web_app_manifest"
        theme_color: "green"
        background_color: "#fff"
        display: standalone
        icons:
            -
                src: /assets/images/avatar.jpg
                sizes: '541x541'
                type: image/jpg
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: '/atom.xml'
navbar:
    menu:
        首页: /
        归档: /archives/
        分类: /categories/
        标签: /tags/
        关于: /about/
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/flc1125/blog.flc.io'
footer:
    copyright: '<a href="https://beian.miit.gov.cn/" target="_blank">粤ICP备15063901号</a>'
    links:
        GitHub:
            icon: fab fa-github
            url: 'https://github.com/flc1125'
        RSS:
            icon: fas fa-rss
            url: /atom.xml
        Sitemap:
            icon: fa fa-sitemap
            url: /sitemap.xml
        Status:
            icon: fa fa-desktop
            url: https://status.flc.io
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        # Creative Commons:
        #     icon: fab fa-creative-commons
        #     url: https://creativecommons.org/
        # Attribution:
        #     icon: fab fa-creative-commons-by
        #     url: https://creativecommons.org/licenses/by/4.0/
        # Noncommercial:
        #     icon: fab fa-creative-commons-nc
        #     url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true
comment:
    type: disqusjs
    shortname: flc-io
    api_key: OyrRHvj9NRXYJPC3GZU1cryqjQONsJhcHdxhEPP1ICSoH6GqtrY1o7s65tDCmbkY
donates:
    -
        type: wechat
        qrcode: '/assets/images/wechat.jpg'
    -
        type: alipay
        qrcode: '/assets/images/alipay.jpg'
# share:
    # type: sharethis
    # install_url: 'https://platform-api.sharethis.com/js/sharethis.js#property=undefined&product=undefined'
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Flc゛
        author_title: 希言自然。
        location: 
        avatar: '/assets/images/avatar.jpg'
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/flc1125
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/flc1125'
            Docs:
                icon: fa fa-book
                url: 'https://docs.flc.io'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        position: left
        type: categories
    -
        position: left
        type: tags
        order_by: name
        amount: 
        show_count: true
    -
        position: right
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: right
        type: recent_posts
    -
        position: right
        type: links
        links:
            FLC: https://flc.io
            文档库: https://docs.flc.io
            粤ICP备15063901号: https://beian.miit.gov.cn/
    -
        position: right
        type: archives
plugins:
    animejs: false
    back_to_top: true
    baidu_analytics:
        tracking_id: ed6f6d8ec4a13c3c200a5f60b8203403
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    # cookie_consent:
        # type: info
        # theme: edgeless
        # static: false
        # position: bottom-left
        # policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: UA-118478085-1
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
